### ISSUE TITLE
Moving from HTTP to HTTPS works, yet there are no assets being returned. 

### ISSUE THREAD

**Issue by thomasbeauvais** [shyim/shopware#10]
Moving from HTTP to HTTPS works with the API, yet there are no assets being returned. The API and admin seem to work just fine. 

The full `APP_URL` = `https://shop.xxx.xxx`

No styles, JS or images are loaded from the default demo store. They work just fine on HTTP.

![Screenshot 2020-11-13 at 15 39 15](https://user-images.githubusercontent.com/1192386/99083830-6436d700-25c6-11eb-9ddc-6f8395eea011.png)

![Screenshot 2020-11-13 at 15 40 19](https://user-images.githubusercontent.com/1192386/99083926-8b8da400-25c6-11eb-9c28-be036afa377e.png)

Also, when the API gives us the product images supplied by Shopware.
![Screenshot 2020-11-13 at 15 41 10](https://user-images.githubusercontent.com/1192386/99084035-abbd6300-25c6-11eb-9ed6-e54baef4227c.png)

Let me know if this is the proper place for such a question, or if I should raise it directly with Shopware support.

Thanks for all your help!

**Comment by shyim** [comment]
./bin/console theme:compile

**Comment by thomasbeauvais** [comment]
But shouldn't this just be done with the container? 

The product images don't have much to do with the theme. Also, this doesn't explain why it works perfectly with http and not https. Nothing else is changed. Very strange.

**Comment by thomasbeauvais** [comment]
Really, this was my bad all of the way. I am just not used to this number of volumes for a container. Generally, I would expect a single one. Hopefully `Shopify will have cloud integration for basic stuff like blob storage. 

Thanks for the help. 

I mounted all of the volumes and everything is fine.

Both problems were 1) the theme getting "compiled" and 2) uploads were being saved into the container.

It might be nice to have in the list of volumes if they are optional or not. Some don't appear needed.

**Comment by shyim** [comment]
I built this image very modular. In Kubernetes or Docker self you can use the same volume multiple times.

As an example for Kubernetes:

/config/jwt => Kubernetes Secret mounted as file
/state, /custom/plugins => A volume
Anything else can be configured by Shopware to write into a Storage like S3 
https://docs.shopware.com/en/shopware-platform-dev-en/how-to/use-s3-datastorage
