### ISSUE TITLE
Docker Installation Failure

### ISSUE THREAD

**Issue by bastianhilton** [shyim/shopware#113]
While i'm attempting to install this docker image i'm getting this error:

databasename.us-east-1.rds.amazonaws.com (0.0.0.143:3306) open
time="2023-08-30T05:13:26Z" level=info msg="load configuration from file" file=/etc/supervisord.conf
time="2023-08-30T05:13:26Z" level=info msg="create process:shopware-empty-cache"
time="2023-08-30T05:13:26Z" level=info msg="create process:php-fpm"
time="2023-08-30T05:13:26Z" level=info msg="create process:nginx"
time="2023-08-30T05:13:26Z" level=info msg="stop listening"
time="2023-08-30T05:13:26Z" level=info msg="try to start program" program=php-fpm
time="2023-08-30T05:13:26Z" level=info msg="try to start program" program=nginx
time="2023-08-30T05:13:26Z" level=info msg="try to start program" program=shopware-empty-cache
time="2023-08-30T05:13:26Z" level=info msg="success to start program" program=shopware-empty-cache
time="2023-08-30T05:13:26Z" level=info msg="program stopped with status:exit status 0" program=shopware-empty-cache
2023/08/30 05:13:26 [notice] 22#22: using the "epoll" event method
2023/08/30 05:13:26 [notice] 22#22: nginx/1.24.0
2023/08/30 05:13:26 [notice] 22#22: OS: Linux 5.10.0-17-cloud-amd64
2023/08/30 05:13:26 [notice] 22#22: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2023/08/30 05:13:26 [notice] 22#22: start worker processes
2023/08/30 05:13:26 [notice] 22#22: start worker process 23
2023/08/30 05:13:26 [notice] 22#22: start worker process 24
[30-Aug-2023 05:13:26] NOTICE: fpm is running, pid 20
[30-Aug-2023 05:13:26] NOTICE: ready to handle connections
time="2023-08-30T05:13:27Z" level=info msg="success to start program" program=php-fpm
time="2023-08-30T05:13:27Z" level=info msg="success to start program" program=nginx
127.0.0.1 -  30/Aug/2023:05:13:56 +0000 "GET /index.php" 500
127.0.0.1 - - [30/Aug/2023:05:13:56 +0000] "GET /admin HTTP/1.1" 500 5 "-" "curl/8.2.1"
2023/08/30 05:13:56 [info] 23#23: *1 client 127.0.0.1 closed keepalive connection

I'm not even getting a migration to the database yet. 

i've redacted my database actual url and IP address 

Any assistance would be greatly appreciated.

**Comment by shyim** [comment]
What are the container arguments?

**Comment by bastianhilton** [comment]
thats the thing when running the docker container through portainer i entered .env variables but they aren't showing up in the local .env in the shopware root directory. How to go about migrating that data into my database?

**Comment by bastianhilton** [comment]
here are my .env variables in the portainer docker container

INSTALL_ADMIN_USERNAME=example
INSTALL_ADMIN_PASSWORD=example
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PHPIZE_DEPS=autoconf 		dpkg-dev dpkg 		file 		g++ 		gcc 		libc-dev 		make 		pkgconf 		re2c
PHP_INI_DIR=/usr/local/etc/php
PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
PHP_LDFLAGS=-Wl,-O1 -pie
GPG_KEYS=1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F 2C16C765DBE54A088130F1BC4B9B5F600B55F3B4
PHP_VERSION=8.0.29
PHP_URL=https://www.php.net/distributions/php-8.0.29.tar.xz
PHP_ASC_URL=https://www.php.net/distributions/php-8.0.29.tar.xz.asc
PHP_SHA256=14db2fbf26c07d0eb2c9fab25dbde7e27726a3e88452cca671f0896bbb683ca9
APP_ENV=prod
LOCK_DSN=flock
MAILER_URL=null://localhost
DATABASE_PORT=3306
SHOPWARE_ES_INDEX_PREFIX=
COMPOSER_HOME=/tmp/composer
SHOPWARE_HTTP_CACHE_ENABLED=1
SHOPWARE_HTTP_DEFAULT_TTL=7200
SHOPWARE_AUTOMATICALLY_EMPTY_CACHE_ENABLED=false
SHOPWARE_EMPTY_CACHE_INTERVAL=86400
BLUE_GREEN_DEPLOYMENT=0
INSTALL_LOCALE=en-GB
INSTALL_CURRENCY=EUR
CACHE_ADAPTER=default
REDIS_CACHE_HOST=redis
REDIS_CACHE_PORT=6379
REDIS_CACHE_DATABASE=0
SESSION_ADAPTER=default
REDIS_SESSION_HOST=redis
REDIS_SESSION_PORT=6379
REDIS_SESSION_DATABASE=1
FPM_PM=dynamic
FPM_PM_MAX_CHILDREN=5
FPM_PM_START_SERVERS=2
FPM_PM_MIN_SPARE_SERVERS=1
FPM_PM_MAX_SPARE_SERVERS=3
PHP_MAX_UPLOAD_SIZE=128m
PHP_MAX_EXECUTION_TIME=300
PHP_MEMORY_LIMIT=512m
PHP_ERROR_REPORTING=E_ALL
RUN_NGINX=1
LD_PRELOAD=/usr/lib/preloadable_libiconv.so php
SHOPWARE_ES_ENABLED=0
SHOPWARE_ES_INDEXING_ENABLED=0
APP_SECRET=example
INSTANCE_ID=example
DATABASE_HOST=example.us-east-1.rds.amazonaws.com
DATABASE_URL=mysql://example:example@example.us-east-1.rds.amazonaws.com:3306/example
SHOPWARE_ES_HOSTS=

**Comment by shyim** [comment]
or have a docker compose file, docker commands you did run. I am not sure if you had set some cmd/entrypoint

**Comment by bastianhilton** [comment]
i used your docker hub install

https://hub.docker.com/r/shyim/shopware

**Comment by bastianhilton** [comment]
the entry point is the default /entrypoint.sh

**Comment by bastianhilton** [comment]
are there migration commands to run within the docker, i see that the information i placed in the docker's .env variables didn't appear in the .env file in the root directory. So once I add the details to the local .env file how do i get shopware to then migrate the data to the database?

**Comment by shyim** [comment]
The docker entrypoint should run the migrations. Tested right now with docker playground it works for me weird. see README example docker compose

**Comment by bastianhilton** [comment]
the docker-compose.yml works from Readme works, thank you.
