### ISSUE TITLE
Dompdf generates blank pdf files

### ISSUE THREAD

**Issue by sawden** [shyim/shopware#13]
Your Shopware 💙 Docker setup helped me a lot!

But I only get blank PDF files in the administration when I try to create invoices or other documents. There seems to be a problem here... but my logs are empty.

I reproduce this problem on two different systems (Windows and Ubuntu) with the simplest configuration from the README.md.

### How to reproduce
1. Start a Shopware instance with the simplest docker-compose.yml
2. Create an Order
3. Open the Administration and go to "Oders" -> "Overview" and select your order.
4. Now scroll to "Documents" and click on "Create new" -> "Invoice".
5. Click on "Preview" or "Create"
6. The PDF is Blank

**Comment by shyim** [comment]
Should be working when https://github.com/shyim/shopware/runs/1546104065 is finished
