### ISSUE TITLE
Caprover install, 500 error

### ISSUE THREAD

**Issue by Saik0Shinigami** [shyim/shopware#14]
This image has a number of issues for me. Maybe this is my inexperience with symphony.

Https throws errors for the shop area only, admin is still accessible. 500 Internal server error. http works fine.
Alternate domains being adding to the image via caprover throws 500 error for the shop both in http and https but admin still works.

Looking at the documentation linked for https terminating proxies, I don't believe that to be the issue here... since it also fails on http traffic for an alternate domain name.

Regardless, I tried the stuff in that documentation as well and see no difference in response.

**Comment by shyim** [comment]
You need to configure in shopware admin all domains. All unkown domains throw a 500 error

**Comment by Saik0Shinigami** [comment]
Of course it's something that simple... Thanks!
