### ISSUE TITLE
Installing packages leads to memory error

### ISSUE THREAD

**Issue by steffenmllr** [shyim/shopware#21]
Hey there,

First of all: thanks for your repo and making shopware more docker friendly!

I'm trying to install a package within the dockerfile as you wrote it in your readme:

```dockerfile
FROM shyim/shopware:6.4

# Add repository
RUN jq '.repositories += [{"type": "composer","url": "https://packages.friendsofshopware.com/","options": {"http": {"header": ["Token: MyToken"]}}}]' /var/www/html/composer.json > /var/www/html/composer2.json && \
  cp composer2.json composer.json && \
  chown 1000:1000 composer.json

RUN sudo -u www-data composer require store.shopware.com/swagcmsextensions

```

this leads to the error:

```
------
 > [3/3] RUN sudo -u www-data composer require store.shopware.com/swagcmsextensions:
#6 0.415
#6 0.415 Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 2258636 bytes) in Unknown on line 0
------
executor failed running [/bin/sh -c sudo -u www-data composer require store.shopware.com/swagcmsextensions]: exit code: 255
```

I've also tried to set the limit to `-1` which did also not work: 
`RUN sudo -u www-data COMPOSER_MEMORY_LIMIT=-1 php -d memory_limit=-1 /usr/local/bin/composer require adyen/adyen-shopware6`

any suggestions ?

**Comment by shyim** [comment]
Hey,

You need to use `sudo -E -u www-data xxx`. The php.ini is based on env variables. Sudo ignores all env vars by default
