### ISSUE TITLE
PHP 8.1 support?

### ISSUE THREAD

**Issue by razvanphp** [shyim/shopware#28]
hello,

Thank you for the image!

Would it be possible to make the php version variable? Would shopware run with PHP 8.1 now? From our test it seems so.

Thank you!
R

**Comment by shyim** [comment]
Hey,

I struggle currently with the build times as building arm64 images takes years. Theoretical it is possible

**Comment by shyim** [comment]
Rewrote the entire image creation.
There are now ags like: 6.4.7.0-php8.0 6.4.7.0-php8.1.
Without PHP version refers always to the lowest supported version
