### ISSUE TITLE
staging environment

### ISSUE THREAD

**Issue by istoOi** [shyim/shopware#34]
Hi,

does this image support a staging environment? 
Using [this Plugin](https://store.shopware.com/emz2686169189745f/staging/testumgebung-1-klick-einrichtung.html) as well as trying various things manually won't work. Shopware doesn't seem to work in a subfolder (eg ...tld/preview). Either the links point to the original system or the pages are completely broken.

**Comment by shyim** [comment]
When you want to use an extension of these, you will need to modify the nginx config to add that.

Also you will need to mount the entire /var/www/html as volume I guess as that plugins are copying files, so you would miss also the auto update by increasing the docker image version


I would suggest duplicating the docker setup and running it under a second subdomain.

**Comment by istoOi** [comment]
Hi.

I'm pretty sure i had the entire folder mounted. Need to confirm that.

"I would suggest duplicating the docker setup and running it under a second subdomain."
The problem is that plugins are licensed under one domain. By running the staging enviroment under a seprerate domain (or even sub domain), the plugins aren't licensed anymore or i need to buy them twice.

**Comment by shyim** [comment]
you dont need. The licensing happens against the license host, which is not the shop host. Also you can run it in a sub path when you have example traefik before it

**Comment by shyim** [comment]
I will close this as I guess its solved :)
