### ISSUE TITLE
updates don't want to run

### ISSUE THREAD

**Issue by COROYO** [shyim/shopware#36]
Hi shyim, 

I think, you are the only who can help me with that. 
We can't upgrade the shopware version in our docker-compose.yml file (based on your advanced-docker file), without getting a fatal error from symphony. We are running Version 6.4.6.1. on PHP 7.4 with MySQL 8, if we want to upgrade to any other version > 6.4.6.1, the frontend throws:

`Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: Class "Shopware\Production\Command\SystemInstallCommand" used for service "Shopware\Production\Command\SystemInstallCommand" cannot be found. in /var/www/html/vendor/symfony/console/DependencyInjection/AddConsoleCommandPass.php:65 Stack trace: #0 /var/www/html/vendor/symfony/dependency-injection/Compiler/Compiler.php(91): Symfony\Component\Console\DependencyInjection\AddConsoleCommandPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #1 /var/www/html/vendor/symfony/dependency-injection/ContainerBuilder.php(744): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #2 /var/www/html/vendor/symfony/http-kernel/Kernel.php(545): Symfony\Component\DependencyInjection\ContainerBuilder->compile() #3 /var/www/html/vendor/shopware/core/Kernel.php(194): Symfony\Component\HttpKernel\Kernel->initializeContainer() #4 /var/www/html/vendor/sh in /var/www/html/vendor/symfony/console/DependencyInjection/AddConsoleCommandPass.php on line 65`

The containers html_task_1 and html_worker_1, as well as html_maintenance_1 are always exiting and restarting.
for example: upgrade to version 6.4.7.0
`[root@**** html]# docker logs maintenance 
rm: can't remove '/var/www/html/config/services/defaults_test.xml': No such file or directory
mysql (192.168.0.2:3306) open

In AddConsoleCommandPass.php line 65:
                                                                               
  Class "Shopware\Production\Command\SystemInstallCommand" used for service "  
  Shopware\Production\Command\SystemInstallCommand" cannot be found.           
`

Thank you for your help

**Comment by shyim** [comment]
Is the cache dir shared or mounted in a folder? 🤔

**Comment by COROYO** [comment]
` volumes:
      - ./plugins:/var/www/html/custom/plugins
      - ./files:/var/www/html/files
      - ./jwt:/var/www/html/config/jwt
      - ./theme:/var/www/html/public/theme
      - ./media:/var/www/html/public/media
      - ./thumbnail:/var/www/html/public/thumbnail
      - ./bundles:/var/www/html/public/bundles
      - ./sitemap:/var/www/html/public/sitemap
      - ./services:/var/www/html/config/services
`

**Comment by COROYO** [comment]
so, delete it?

**Comment by shyim** [comment]
https://github.com/shopware/production/commit/4a0cd7c022c3971d7e8dacaa4a1ec5fa6c954f2e

Apply that to your folder or remove it

**Comment by COROYO** [comment]
with shyim/shopware:latest i'm getting now:

`[root@4AE3720 html]# docker logs maintenance
Written
mysql (192.168.96.4:3306) open

In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
                                                                               
  The service "Swag\LanguagePack\Core\System\SalesChannel\Command\SalesChanne  
  lCreateCommand" has a dependency on a non-existent service "Shopware\Core\M  
  aintenance\SalesChannel\Service\SalesChannelCreator".                        
                                                                              `

**Comment by shyim** [comment]
I guess you have to update the SwagLanguagePack plugin

**Comment by COROYO** [comment]
Ok I got it. I downloaded a new shopware:latest image, and now it's updating and running. Thank you very much <3

**Comment by shyim** [comment]
no problem xD
