### ISSUE TITLE
bin/watch-storefront.sh webpack-dev-server: not found

### ISSUE THREAD

**Issue by Zerotask** [shyim/shopware#39]
**Describe the bug**
![image](https://user-images.githubusercontent.com/20150243/174295949-d0d50e58-69c5-468f-99d9-195599c9429f.png)

bin/watch-storefront.sh is working tho.

When I log in to the container and do a `npm i` I can run bin/watch-administration.sh. 

**To Reproduce**
1. Open CLI from the container
2. Run bin/watch-administration.sh

**Expected behavior**
Admin watcher is starting without problems.

**Environment:**
 - OS: [e.g. Ubuntu 20.04] WSL2 Ubuntu 20.04 with docker image shyim/shopware:6.4.11-php8.0
 - Docker Version: 4.9.1

**Comment by shyim** [comment]
It should install them with that script here https://github.com/shopware/production/blob/6.4/bin/build-administration.sh#L49
