### ISSUE TITLE
Define "error_reporting" via environment variable

### ISSUE THREAD

**Issue by Zerotask** [shyim/shopware#51]
**Is your feature request related to a problem? Please describe.**
Shopware/Symfony are throwing a lot of deprecated exceptions lately which makes it hard to read log files.

**Describe the solution you'd like**
a simple env var to set a custom error_reporting for PHP (or any other similar solution).
And yes I know how to create my own image based on your image and modify it on my own, but that's not what I want to do.

**Additional context**
Using 6.4.16.0-php8.0

Was (again) confused about the 2 similar repositories :D (https://github.com/shyim/shopware-docker/issues/171)

**Comment by shyim** [comment]
Are you in APP_ENV=prod?

They should be shown only in dev 🤔

**Comment by Zerotask** [comment]
I'm in APP_ENV=dev and my request was especially for that
