### ISSUE TITLE
[QUESTION] How can we dockerize the static plugins?

### ISSUE THREAD

**Issue by KennyDizi** [shyim/shopware#59]
Hi @shyim, I would like to ask how can we combine the plugins when we build the docker-compose file?
eg: https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor, https://github.com/FriendsOfShopware/FroshLazySizes, https://github.com/FriendsOfShopware/FroshPlatformHtmlMinify

**Comment by shyim** [comment]
Hey,

I would recommend you create an own Dockerfile [like in this project](https://github.com/shyim/shopware/blob/main/shopware/8.1/6.4.19.0/Dockerfile) and copy your existing local Shopware project into it. So it should work then out of the box :)
