### ISSUE TITLE
Feature request: add xdebug (configurable via environment variables)

### ISSUE THREAD

**Issue by Zerotask** [shyim/shopware#63]
Would be great to have xdebug pre-installed and configurable via environment variables

**Comment by shyim** [comment]
Hey,

I would like to hold this docker image small as possible. It was also intended to be used in production. So, If you want to use xdebug, I can recommend you creating your own local docker image by using this as source. Like

```
FROM shyim/shopware:xxxx

RUN install-php-extensions xdebug
```

That should be already enough, you can refer to that Dockerfile also directly in docker-compose. See also https://docs.docker.com/compose/compose-file/build/
