### ISSUE TITLE
[Question] Any tips for migrating to docker?

### ISSUE THREAD

**Issue by Fernien** [shyim/shopware#64]
Hi i want to migrate a shopware 6 v6.4.18 to docker. I tried copying the files from these directories

/var/www/html/files | Documents and other private files
/var/www/html/var/log | Logs
/var/www/html/public/theme | Compiled theme files
/var/www/html/public/media | Uploaded files
/var/www/html/public/bundles | Bundle Assets
/var/www/html/public/sitemap | Sitemap
/var/www/html/public/thumbnail | Generated Thumbnails
/var/www/html/config/jwt

to the docker container and also importing the database with no success.
First try: 
The source system had mariadb 10.3 and the destination (docker) mysql 5.7 which led to import errors. 

Second try:
Using mariadb within docker. This time i didn't get any import errors but the site was blank.

Couldn't find any problems in browser console, docker log or traefik logs. Does someone has any idea what i am doing wrong ?

Thanks!

**Comment by MarslMarcello** [comment]
Have you tried to ask in the Slack Community too? https://shopwarecommunity.slack.com/archives/C02DCPX35L4
So none of your logs is telling you anything? Nothing went wrong? Like no docker logs from app or db is saying anything?

**Comment by shyim** [comment]
I will close this as it is inactive
