### ISSUE TITLE
Migration error starting container

### ISSUE THREAD

**Issue by thomasbeauvais** [shyim/shopware#7]
`You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)"`

I am not sure why I need SUPER privileged nor why it's creating a database. I already gave it a database with admin rights. We do not get SUPER rights for most cloud-managed databases.

[shopware-container-errors-00.txt](https://github.com/shyim/shopware/files/5392325/shopware-container-errors-00.txt)

**Comment by shyim** [comment]
Should be fixed with the newest built and disabling blue green. Set BLUE_GREEN_DEPLOYMENT to 0 and the Installation should work

**Comment by thomasbeauvais** [comment]
Seems to have worked, at least the error is gone. Thanks!

```
shopware    |  ---------- ----------------------
shopware    |   Action     Number of migrations
shopware    |  ---------- ----------------------
shopware    |   Migrated   286 out of 286
shopware    |  ---------- ----------------------
```
