### ISSUE TITLE
How to disable User Deprecated: Since shopware/core messages?

### ISSUE THREAD

**Issue by Zerotask** [shyim/shopware#72]
How to disable Shopware's user deprecated ErrorException completely?

I tried a couple of things related to Symfony, Monolog and PHP but nothing worked.

Especially when using commands, it's really hard to properly read output when you constantly get blocks of deprecated.

![image](https://user-images.githubusercontent.com/20150243/220470574-f6f0ef1e-5830-4a61-9aa8-7b42101488f3.png)

**Comment by shyim** [comment]
APP_DEBUG=0

**Comment by Zerotask** [comment]
I already tried that without success.

**Comment by wv-leifel** [comment]
@Zerotask I'm currently using this monolog config to hide these messages. It's displaying the output of the command and errors as far as i tried but i don't know if it hides something important, so use with care.
`monolog:
  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: error
      channels: ["!event","!doctrine"]
    console:
      type:   console
      process_psr_3_messages: false
      level: error
      channels: ["!event", "!doctrine", "!console", "!php", "!messenger"]`

Just mount it to /var/www/html/config/packages/dev/monolog.yaml

**Comment by shyim** [comment]
As it is not related to this docker image I will close this
