### ISSUE TITLE
Getting error after shopware6 containers gets ready

### ISSUE THREAD

**Issue by devphoenix2404** [shyim/shopware#75]
Hi Team,

I am facing an issue, where on the container log i am getting the below error

`--
Set and compiling theme "Storefront" (1294....) as new theme for sales channel "Headless"
Set and compiling theme "Storefront" (1294.....) as new theme for sales channel "Storefront"
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x7f8198d6896e]
runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7f8198d6896e

runtime.throw(0x8cd2c4, 0x2a)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime: unexpected return pc for runtime.sigpanic called from 0x7f8198d6896e

runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:726 +0x4ac
goroutine 1 [runnable]:
runtime.main()
	/usr/local/go/src/runtime/proc.go:114
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1
--`

Container is executed the installation script successfully only after that when try to access the shop we are getting 503 service not available.
Image is shyim/shopware:6.4.20.0

`FROM shyim/shopware:6.4.20.0

ARG APP_ENV
ENV APP_ENV=${APP_ENV}
ARG APP_SECRET
ENV APP_SECRET=${APP_SECRET}
ARG INSTANCE_ID
ENV INSTANCE_ID=${INSTANCE_ID}

ARG APP_URL
ENV APP_URL=${APP_URL}

ARG MYSQL_DB_HOST
ENV DATABASE_HOST=${MYSQL_DB_HOST}
ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_DATABASE
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

ARG ADMIN_USERNAME
ENV INSTALL_ADMIN_USERNAME=${ADMIN_USERNAME}
ARG ADMIN_PASSWORD
ENV INSTALL_ADMIN_PASSWORD=${ADMIN_PASSWORD}

COPY .docker/shopware.conf /etc/nginx/sites-enabled/shopware.conf`

**Comment by shyim** [comment]
I updated supervisord and compiled it with Go 1.20 and it works for me. So I will close this.

**Comment by devphoenix2404** [comment]
What changes you made? May you please share with us so that we can implement the same. @shyim
