### ISSUE TITLE
How to ignore the APP_URL? 

### ISSUE THREAD

**Issue by thomasbeauvais** [shyim/shopware#8]
The APP_URL is something that is causing a bit of a problem.

We are trying to hose this in an Azure Container Instance Group where there is an Application Gateway that exposes the cluster. There is a health check that is coming from the various front-end load balancers with different IP and no hosts.

Shopware is constantly returning a 500 thus the health check fails.

The best option would be to remove this APP_URL altogether since there are many network layers that we will not be able to guarantee.

Another option might be to provide a 200 OK endpoint if the container is running. 

At this point, I am blocked.

Any insight would be appreciated. Thanks!
```

10.1.3.7 - - [03/Nov/2020:21:49:32 +0000] "GET / HTTP/1.1" 500 843 "-" "-"
2020/11/03 21:49:32 [info] 60#60: *11 client 10.1.3.7 closed keepalive connection
127.0.0.1 -  03/Nov/2020:21:49:49 +0000 "GET /index.php" 500
10.1.3.4 - - [03/Nov/2020:21:49:49 +0000] "GET / HTTP/1.1" 500 843 "-" "-"
2020/11/03 21:49:49 [info] 60#60: *13 client 10.1.3.4 closed keepalive connection
127.0.0.1 -  03/Nov/2020:21:49:50 +0000 "GET /index.php" 500
10.1.3.9 - - [03/Nov/2020:21:49:50 +0000] "GET / HTTP/1.1" 500 843 "-" "-"
2020/11/03 21:49:50 [info] 60#60: *15 client 10.1.3.9 closed keepalive connection
```

**Comment by shyim** [comment]
I never used the Azure. I guess it don't use this Healthcheck here?
https://github.com/shyim/shopware/blob/master/Dockerfile#L82

Maybe route that to /admin if possible. /admin is accessible from any host

**Comment by thomasbeauvais** [comment]
I have been using the /admin as a health check and it works fine now. I am concerned about exposing the /admin to the world, though that is something I can iron out later through load balancer rules and security groups (hopefully).

Thanks again for the speedy response!

Now, I am getting this error every once in a while and I am not sure what to do with it. A restart resolves it.
`{"errors":[{"code":"0","status":"500","title":"Internal Server Error","detail":"Key path \u0022file:\/\/\/var\/www\/html\/config\/jwt\/public.pem\u0022 does not exist or is not readable"}]}`

**Comment by thomasbeauvais** [comment]
Deleting the "installed_version" and restarting resolves this issue. 

Perhaps the version upgraded and this causes a bug? I should be able to use "latest" during development without downtime. Can you please provide some insight on how to combat this in the future?

**Comment by shyim** [comment]
There are files under `/var/www/html/config/jwt` they needs to be shared. On Kubernetes I have them in a Secret and mount them as files

**Comment by thomasbeauvais** [comment]
Alright, what I am not understanding is that if I delete the installed_version, then it works. The problem only occurs when there is a restart.

If it doesn't work, it should not work always?

Anyway, we are (currently) using HTTP with Shopware in a private network and wrapping that in a public HTTPS load balancer. Of course, before go-live we will want to provide these keys as files. 

Is there a quick want to do this? It seems that I need to create a share for `/var/www/html/config/jwt`, trigger a reset in by removing the `installed_version` and then the nodes should share that rather than keeping in on the container, correct?

**Comment by shyim** [comment]
You can create a share for `config/jwt` to share it everywhere. Or use something like secrets in k8s in kubernetes to place that files in any pod.

You can generate that files by executing `bin/console system:generate-jwt-secret` in the container

**Comment by thomasbeauvais** [comment]
Thanks, that worked.
